### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by Marsietis** [packcord/discord-giveaways#4]
hey, I'm using npm package for this with "npm install --save discord-giveaways" command and I'm getting this error 
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:

**Comment by Marsietis** [comment]
In log's file it says this "28 verbose stack Error: Invalid dependency type requested: alias"

**Comment by Androz2091** [comment]
Hello
It's strange, can you give me more information, please? (operating system, Nodejs version, and npm version)
Apparently, one way to get around this problem is to use Yarn instead of Npm. Try it with this to see if it solves the problem.

**Comment by Marsietis** [comment]
Could you give me your discord?

**Comment by Androz2091** [comment]
Here is the link: https://discord.atlanta-bot.fr
I'm Androz#1532

**Comment by Androz2091** [comment]
Closed due to inactivity...
